# Generated by Django 3.0.7 on 2020-10-21 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nazarsanji',
            name='isRead',
            field=models.BooleanField(default=False),
        ),
    ]
