# Generated by Django 3.1.2 on 2020-10-07 10:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_news_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='publish',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
