# Generated by Django 3.1.1 on 2020-10-09 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_blog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'News'},
        ),
    ]
