# Generated by Django 3.0.7 on 2020-10-20 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20201017_1649'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'New', 'verbose_name_plural': "New's"},
        ),
    ]
